---

- name: packages
  apt: >
    name={{ item }}
    state=present
  with_items:
    - mysql-server
  sudo: yes

- name: service
  service: >
    name=mysql
    state=started
    enabled=yes
  sudo: yes
