---

- name: packages
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - mysql-server
  when: ansible_os_family == "Debian"
  sudo: yes

- name: service
  service: >
    name=mysql
    state=started
    enabled=yes
  sudo: yes
